# vim: set tabstop=4 shiftwidth=4 noexpandtab
# ================================================================

# For this example,  Sail compile order is important.
#	The ending of scattered definitions appear in scattered_definitions_end.sail,
#	so this must be the last file.
SAIL_SRC	:=  scattered_definitions_begin.sail \
				scattered_definitions.sail \
				a.sail \
				b.sail \
				scattered_definitions_end.sail

include ../Makefile.generic

