# vim: set tabstop=4 shiftwidth=4 noexpandtab
# ================================================================
# Filename:		Makefile
#
# Description:	Makefile for building.....
#
# Author(s):	Bill McSpadden (william.c.mcspadden@gmail.com)
#
# Revision:		See revision control log 
#
# ================================================================


#==============
# Includes
#==============



#==============
# Make variables
#==============
SAIL_PATH 		:= /home/billmc/.opam/default
SAIL_BIN		:= ${SAIL_PATH}/bin
SAIL_LIB		:= ${SAIL_PATH}/lib/sail
#SAIL			:= ${SAIL_BIN}/sail
SAIL			:= ../../../sail
SAIL_OUTFILE	:= out
SAIL_FLAGS		:= -c -o ${SAIL_OUTFILE}

# TODO:  fix this.  Need to find an installation home for these C files.
# 		Perhaps compile a library?
#SAIL_DIR		:= /home/billmc/riscv/riscv_sail.git
#SAIL_DIR		:= /home/billmc/riscv/riscv_sail__billmcspadden-riscv.git
SAIL_DIR		:= ../../..

SRC				:= hello_world.sail

CC				:= gcc
CCFLAGS			:= -lgmp -lz -I ${SAIL_DIR}/lib/ -o out
C_SRC			:= out.c ${SAIL_DIR}/lib/*.c


TARGET			:= out

#==============
# Targets and Rules
#==============

all: run


build: out


install:

run: out
	./out


out: out.c
	gcc out.c ${SAIL_DIR}/lib/*.c -lgmp -lz -I ${SAIL_DIR}/lib -o $@


#	${CC} ${CCFLAGS} $<

out.c: ${SRC}
	SAIL_DIR=${SAIL_DIR} ; export SAIL_DIR ; \
	${SAIL} ${SAIL_FLAGS} ${SRC}




# clean:  cleans only local artifacts
clean:
	rm -f out out.c out.ml

# Cleans local artifacts and the install location
clean_all:



