= A Sail Cookbook:  Recipes for Small Bytes (Bill)
:doctype: book

== Table of Contents

:toc:


- [Introduction](#introduction)

== List of programming examples

- ["Hello, World!"](#hello-world-example-program-bill)

:sectnums:
== Introduction

Sail is a programming language that was developed for the purpose
of clearly, concisely and completely describing a computer's 
Instruction Set Architecture (ISA).  This includes...
- specifying the opcodes/instructions and their behaviours
- specifying the general purpose registers
- specifying the control space registers

Sail was the language chosen by RISC-V International to formally
specify the RISC-V open source
ISA.  This docuement,  while not RISC-V specific,  is especially targeted for engineers who are working on specifying the RISC-V
ISA. 

This cookbook is intended to supply the beginning Sail programmer with
some simple, well-commented, bite-size program fragments that can
be compiled and run.

**github** is used to host the development of Sail.  You can find the 
repository at the following URL:

https://github.com/rems-project/sail

Currently,  the work on this cookbook can be found on a branch in the
above repo.  This branch is:

https://github.com/billmcspadden-riscv/sail/tree/cookbook_br

So this is the place you should probably clone.  (Eventually,  this
branch will be merged to the release branch.)

Other documentation:

There is another useful Sail document that you should know about.  It is
"The Sail instruction-set semantics specification language" by Armstrong, et. al.  It can be found at:

https://github.com/billmcspadden-riscv/sail/blob/cookbook_br/manual.pdf

While useful,  the document does not contain a useful set of programming
examples.  That is the purpose of *this* document.


== How to contribute (Bill)


=== pull requests (Bill)

=== RISC-V working groups (Bill)

=== style and contribution guide

=== brevity

=== short executable

=== standalone

=== maintainership (when something breaks)

=== Syntax highlighting for Sail

Syntax highlighting for several editors (emacs, vim, Visual Studio, etc)
can be found at:

https://github.com/rems-project/sail/tree/sail2/editors



== Sail installation
=== Docker

TBD

=== Ubuntu (Bill Mc.)

=== MacOS (Martin)

=== Windows 
Support of a native command line interface is not planned.  If you
want to run Sail under Windows,  plan on running it under Cygwin.

=== Windows: Cygwin (Bill Mc.,  low priority)

If there is a demand,  a port to Cygwin will be attempted.

=== Other?

Are there other OS platforms that should be supported?
Other Linux distis?  Or will Docker support?

== Basic description
=== what sail is
- sequential model only
- non-parallel

=== what sail is not 
- not a RTL language, etc
- Sail does not support any parallelism.  No threads.  No event sequences.  No clocking.

=== version management and what to expect


== “Hello, World” example program (Bill)
All example programs associated with this cookbook, can be found
in <sail_git_root>/cookbook/functional_code_snippets/

The purpose of this simple program is to show some of the basics
of Sail and to ensure that you have the Sail compiler (and the other
required tools) installed in your environment.

It is assumed that you have built the sail compiler in the local 
area. The Makefiles in the coding examples depend on this.

The following code snippet comes from: 

https://github.com/billmcspadden-riscv/sail/tree/cookbook_br/cookbook/functional_code_snippets/hello_world

hello_world.sail:

// include doesn't appear to render in github
// Therefore, asciidoctor-reducer will be used to create
// a complete (all files included) file, which will be
// committed by git.  

[source, sail]
----
include::../functional_code_snippets/hello_world/hello_world.sail[]
----

So... that's the code we want to compile.  But how do we compile it?
Remember, we want to use the sail compiler that was built in this 
sandbox.  We use a 'make' methodology for building.  The first Makefile
(in the same directory as the example code example) is very simple.
It includes a generic Makefile (../Makefile.generic) that is used
for building most of the program examples.


[Note]  If you want to create and contribute your own example program
and you need to deviate from our make methodolgy,  you would do that
in your own test directory by writing your own Makefile.

The basic flow is: + 
*.sail  --(Sail)--> out.c, *.c --(gcc)--> executable


Makefile:

[source, makefile]
----
include::../functional_code_snippets/hello_world/Makefile[]
----


Makefile.generic is the Makefile that does the work for compilation.
It depends on a local compilation of sail. See the [Installation](#sail-installation)
section to understand how to install in the tools for your platform.

Makefile:

[source, makefile]
----
include::../functional_code_snippets/Makefile.generic[]
----

What does the compilation process look like?  Under Ubuntu Linux,  this
is the output you can expect for compiling and running the "hello world"
example program.

```
ubuntu-VirtualBox 227> make
SAIL_DIR=../../.. ; export SAIL_DIR ; \
../../../sail -c -o out hello_world.sail
gcc out.c ../../../lib/*.c  -lgmp -lz -I ../../../lib/ -o out
./out
hello, world!
hello, another world!
ubuntu-VirtualBox 228> 

```

Now that we've examined the Makefiles,  we will make little mention of them
in the rest of this document (except for the example where we discuss the 
C foreigh function interface where we will show how Sail can call C functions).

== Data types
=== effect annotations
=== Integers
=== Bits
=== Strings
=== Lists
=== Structs
=== mappings
=== Liquid data types (Martin)

== Execution
=== Functions
=== Control flow
=== Iteration 
=== matches

== Description prelude.sail
=== description of print, sext, equility etc.  standard template stuff
=== the C interface

== CPU example
- From nand2tetris


== Formal tools that analyze Sail source code
<template>
coverage
