:doctype: book
:sectids:
The Sail Programming Language: A Sail Cookbook
==============================================
William C. McSpadden <bill@riscv.org>; Martin Berger <contact@martinfriedrichberger.net>
:toc:
:toc-placement: preamble
:toclevels: 2

:showtitle:


// Need some preamble to get TOC
{empty}

== List of programming examples (in increasing complexity)

The main purpose of this document,  is to give the user a quick 
reference to Sail coding examples. The following is a list of 
all the programming examples found in this document.

<<hello_world>>

<<my_replicate_bits>>



:sectnums:
== Introduction

Sail is a programming language that was developed for the purpose
of clearly, concisely and completely describing a computer's 
Instruction Set Architecture (ISA).  This includes...
- specifying the opcodes/instructions and their behaviours
- specifying the general purpose registers
- specifying the control space registers

Sail was the language chosen by RISC-V International to formally
specify the RISC-V open source
ISA.  This docuement,  while not RISC-V specific,  is especially targeted for engineers who are working on specifying the RISC-V
ISA. 

This cookbook is intended to supply the beginning Sail programmer with
some simple, well-commented, bite-size program fragments that can
be compiled and run.

**github** is used to host the development of Sail.  You can find the 
repository at the following URL:

https://github.com/rems-project/sail

Currently,  the work on this cookbook can be found on a branch in the
above repo.  This branch is:

https://github.com/billmcspadden-riscv/sail/tree/cookbook_br

So this is the place you should probably clone.  (Eventually,  this
branch will be merged to the release branch.)

Other documentation:

There is another useful Sail document that you should know about.  It is
"The Sail instruction-set semantics specification language" by Armstrong, et. al.  It can be found at:

https://github.com/billmcspadden-riscv/sail/blob/cookbook_br/manual.pdf

While useful,  the document does not contain a useful set of programming
examples.  That is the purpose of *this* document.


== How to contribute (Bill)


=== pull requests (Bill)

=== RISC-V working groups (Bill)

=== style and contribution guide

=== brevity

=== short executable

=== standalone

=== maintainership (when something breaks)

=== Syntax highlighting for Sail

Syntax highlighting for several editors (emacs, vim, Visual Studio, etc)
can be found at:

https://github.com/rems-project/sail/tree/sail2/editors

It is beyond the scope of this document to describe how to use
the syntax highlighting for the various editors.

== Sail installation
=== Docker

TBD

=== Ubuntu (Bill Mc.)

TBD

=== MacOS (Martin)

TBD

=== Windows 
Support of a native command line interface is not planned.  If you
want to run Sail under Windows,  plan on running it under Cygwin.

=== Windows: Cygwin (Bill Mc.,  low priority)

If there is a demand,  a port to Cygwin will be attempted.

=== Other?

Are there other OS platforms that should be supported?
Other Linux distis?  Or will Docker support?

== Basic description
=== what sail is
- sequential model only
- non-parallel

=== what sail is not 
- not a RTL language, etc
- Sail does not support any parallelism.  No threads.  No event sequences.  No clocking.

=== version management and what to expect

[#hello_world]
== “Hello, World” example program (Bill)
All example programs associated with this cookbook, can be found
in <sail_git_root>/cookbook/functional_code_snippets/

The purpose of this simple program is to show some of the basics
of Sail and to ensure that you have the Sail compiler (and the other
required tools) installed in your environment.

It is assumed that you have built the sail compiler in the local 
area. The Makefiles in the coding examples depend on this.

The following code snippet comes from: 

https://github.com/billmcspadden-riscv/sail/tree/cookbook_br/cookbook/functional_code_snippets/hello_world

hello_world.sail:

// include doesn't appear to render in github
// Therefore, asciidoctor-reducer will be used to create
// a complete (all files included) file, which will be
// committed by git.  

[source, sail]
----
include::../functional_code_snippets/hello_world/hello_world.sail[]
----

So... that's the code we want to compile.  But how do we compile it?
Remember, we want to use the sail compiler that was built in this 
sandbox.  We use a 'make' methodology for building.  The first Makefile
(in the same directory as the example code example) is very simple.
It includes a generic Makefile (../Makefile.generic) that is used
for building most of the program examples.


[Note]  If you want to create and contribute your own example program
and you need to deviate from our make methodolgy,  you would do that
in your own test directory by writing your own Makefile.

The basic flow is: + 
*.sail  --(Sail)--> out.c, *.c --(gcc)--> executable


Makefile:

[source, makefile]
----
include::../functional_code_snippets/hello_world/Makefile[]
----


Makefile.generic is the Makefile that does the work for compilation.
It depends on a local compilation of sail. See the [Installation](#sail-installation)
section to understand how to install in the tools for your platform.

Makefile:

[source, makefile]
----
include::../functional_code_snippets/Makefile.generic[]
----

What does the compilation process look like?  Under Ubuntu Linux,  this
is the output you can expect for compiling and running the "hello world"
example program.

```
ubuntu-VirtualBox 227> make
SAIL_DIR=../../.. ; export SAIL_DIR ; \
../../../sail -c -o out hello_world.sail
gcc out.c ../../../lib/*.c  -lgmp -lz -I ../../../lib/ -o out
./out
hello, world!
hello, another world!
ubuntu-VirtualBox 228> 

```

Now that we've examined the Makefiles,  we will make little mention of them
in the rest of this document (except for the example where we discuss the 
C foreign function interface where we will show how Sail can call C functions).

=== "Hello, World" and the Sail interactive interpretter

TBD

== Data types
=== effect annotations
=== Integers
- Int
- int
- Multi-precision

=== type variables
What does " 'n " mean?

=== Bits

=== Strings

=== Lists

=== Structs

=== mappings

=== Liquid data types (Martin)

== Execution
=== Functions




[#my_replicate_bits]
=== The ``my_replicate_bits()`` function from the Sail manual (Bill)

First,  let's look at the code that is described in the Sail manual for the function, my_replicate_bits().  

Note:
The following code actually comes from the file doc/examples/my_replicate_bits.sail.  It is a little bit different than what is shown in the manual for reasons that will be covered here.

[source, sail]
----
include::../functional_code_snippets/sail_manual_example_my_replicate_bits/my_replicate_bits.sail[]
----

You will see in this code,  that there is no 'main' function,  and as such, will not compile into a C Sail model.  You will get the following error message:

TODO: get the error message.

In order to get this to compile into a C Sail model,  you will need to provide a main function.  The following code shows the implementation of a ``main()`` function that calls my_replicate bits().

[source, sail]
----
include::../functional_code_snippets/sail_manual_example_my_replicate_bits/main.sail[]
----

Because both the files, my_replicate_bits.sail and main.sail, need to have the function signatures in order to compile (and we want them to be consistent),  the function signatures have been put into a seperate file that is include by both.  Here is the function signature file, my_replicate_bits_function_signatures.sail:

[source, sail]
----
include::../functional_code_snippets/sail_manual_example_my_replicate_bits/my_replicate_bits_function_signatures.sail[]
----


=== Control flow
=== Iteration 
- for
- while
- lamba function

=== matches

== Other stuff

===  __FILE__ , __LINE__ , __LOC__

== Description prelude.sail

prelude.sail contains the function signatures and implemenmtations
of many support functions.  

=== description of print, sext, equility etc.  standard template stuff
=== the C interface

== CPU example
- From nand2tetris


== Formal tools that analyze Sail source code

coverage

== FAQs (Frequently Asked Questions)

Following are a set of FAQs that were generated via set of questions to the Sail developers.

include::./FAQ_RISCV_model.adoc[]

